### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by thexravenx** [nemosminer/NemosMiner-v2.5.2-linux-HIVE-OS#2]
Recent error running the start script. 

HiveOS version Version: 0.5-36

Stopping screen session 15745
Traceback (most recent call last):
  File "./swap_ccminer.py", line 10, in <module>
    data2 = json.loads(lines[0])
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by thexravenx** [comment]
Closing issue. Reinstalling HiveOS allowed it to connect. Odd, but not duplicate anymore.
